
# Book Notes



## Book 1

Fascism, a warning. Madeleine Albright & Bill Woodward. (2018). _Williams Collins_.

- 'lock up' rivals, journalists = enemy of the people, immigrants are villains
- nationalistic economic & trade policies

Italy 1920s Fascists:
- political left = advocated dictatorship of dispossessed
- political center = return to absolute monarchy
- political right = authoritarian corporate state 

German Nat'l Social Party {Nazis}
obviously anti-semite, but also immigration and capitalism
were pro old age pensions and more education for the poor


> Fascism draws energy from [people] who are upset because of a lost war, lost job, some kind of humiliation or a sense their country is in steep decline. the more pain and resentment the easier it is for fascism to promise to take back what was stolen.

Italy grew in fascists due to social problems and Mussolini urged followers to reject capitalism

Fascists vs Socialists:
fascists grew in jobless volunteers who trashed newspaper offices, beat up workers and peasants and police ignored these actions


p.24 Mussolini initiated a campaign to _drenare le palude_ "drain the swamp" by firing more than 35,000 civil servants

1924 Mussolini electoral reform => fascist control
1926 Mussolini abolished political parties , freedom of the press, neutered labor movement, took control of Nat'l Police which led to internal surveillance

Fascist credo "Believe! Obey! Fight!"

Mussolini 
- urged followers to "live dangerously" by renouncing all comforts 
- was a poor listener who did not like when others talked
- did not understand how interest rates worked 


Hitler
- promised to not disrupt freedom of speech, parliament, the church
- arrested socialists
- used same verbs: smash, destroy, annihilate, kill
- capitalized on the Great Depression era economics to promise Germany a better future
- sent the SA to beat up political opponents and put them in to concentration camps
- disposed of unions, banned Jews from professions
- put the arts & radio were under Joseph Goebbels control
- radio was main way to spread propaganda (the internet of 1930s)
- lied all the time about himself and about his enemies
- 

Mussolini met Hitler but Mussolini rejected hitler's racist ideas

1931 Francisco Largo Cabellero in Spain was put in power by help of Hitler & Mussolini, got military help from Stalin . Cabellero benefited from Spain social, political and economic unrest 


post WWI Austro-Hungary, the Bolsheviks took power 
- there was massive poverty
- several Fascists groups arose
- Arrow Cross = pro "Hungarism", promised: jobs, revenge, freedom from foreigners, eternal salvation, restore stolen territory
- 1939 it was the largest right wing party
- Arrow Cross sent armed teens into streets to terrorize population, worked Jews to death or deported them by train or just killed them
- Anti-semitism rose across society, politics, academia


- France had blue shirts Solitaire Francais right wing group , pro Nazi , slogan "France for the French"

- Iceland Nat'l Party wore grey shirts , red swastika armbands, believed in the Aryan supremacy but got <1% vote

- Czechoslovakia Konrad Henlein joined Nazism, followers wore white shirts

- Fascism: poor economy + political ambition + prejudice

- Asheville, North Carolina Legion wore blue pants, silver shirts w/ "L" = love, loyalty, liberty. antisemitic. laid the groundwork for the KKK

- 1928 Fritz Kuhn Germany -> USA, started German Amer. Bund, brown shirts, black boots, swastikas. went to jail for tax evasion and embezzling GAB $ to support a mistress 

vituperative = using, containing harshly critical or irate language


- Stalin soviets used Fascist to discredit capitalists, nationalists, democrats, religious, socialist and liberals

- 1932 Mussolini define Fascism " the state is all embracing and no human or spiritual values can exist" (p.78)

- Nazis: Race & Nationality
- Communism: class

- common language = violence

- equate obedience with virtue, become robots with the barage of propaganda 

- quest for money, property, pleasure, worker vs worker
- under Stalin arrests of Jews labelled traitors, enemies of the people, running dogs, pigs, imperial spies








## Book 2

Hitler's Social Revolution. Class and Status in Nazi Germany 1933-1939. David Schoenaum. Doubleday & Company. 1966. 

```{r,warning=FALSE}
# German Occupational Distribution in % of Population, p.3
library(tidyverse)

df = tribble(
  ~'Year', ~'Agriculture', ~'Industrial', ~'Services',
  1882, 42, 36, 22,
  1895, 36, 39, 25,
  1907, 34, 40, 26,
  1925, 30, 42, 28,
  1933, 29, 41, 30
)

df


```


- 1923 Germany had hyperbolic inflation
- 1929-30 recession economy
- Nazi appeal to make things better: econ dissatisfaction, loss of export market, exhaustion of raw & plant materials
- Hitler support was from unemployment and inflation concerns
- 1926 Hitler's speech in Hamburg addresses audience as "Gentleman" and no as comrades. "those who revolted in the home front were not Burger but scum, traitorous scum"
- Hitler labelled critics of anti-Jewish ideology as 'bourgeois cowards'






## Book 3

Lenin, Stalin, and Hitler. the age of social catastrophe. Robert Gellately. 2007. Vintage Books.

- 1918/1919 central Euro has socialist and communist revolutions start post WWI
- political violence, coups, general instability
- Hitler was aware of the resentment and bitterness that swept Germany
- Hitler spread hate for "November criminals" who are blamed for Germany's loss and wanted to tear up the Treaty of Versailles (peace treaty between with the Allied forces, Article 231 "war guilty clause")
- Hitler Aug 13, 1920 speech was to envision Germany full potential except for the Jews, who were viewed as the destroyers of German culture
- Hitler was charasmatic, easily talked to the masses 
- Stalin had no charisma, was a pencil pusher
- Stalin & Lenin did not appeal to public opinion or try to build on popularity
- Hitler believed you needed popularity
- Hitler had contempt for Soviet dictators and their terror used on its people, Hitler wanted to win the hearts and minds of Germans and bond over the anti-Jewish views and exclusion
- Hitler was anti-Communism
- promise of material gain and improvement led to communism & nazism
- the Third Reich profiteering and corruption had no limits, special perks for those in the inside fold and on a 'list' 
- 1917 Feb 23 , Petrograd. peaceful march for Women's right's "down with the tsar!" (Nicolas II) and on Feb 26 the tsar ordered protesters to be fired on
- 1917 Lenin's slogan "peace, land and bread" which was the Bolshevik agenda
- Lenin promised peasant soldiers to give them land "without payment" which won over the majority for the Bolshevik cause
- 1918/19 Lenin ruled by terror, draconian measures, hanged enemies, published their names, took all their grain
- Leon Trotsky was right hand man to Lenin
- Jan 14 1918 amind a famine Lenin called the wealthier peasants kulaks and had very negative views which was not new, anyone could be called this and Lenin opposed them and their revolts
- common phrases in the White Army (fringe group of Russia unlike the Red Army which aimed to restore lands) was "beat the Jews and save Russia", "death to the Jews and communists","Jews and Russians get out of Ukraine"
- the White Army killed Jews , thought of as "microbes" and a "social disease" to be eliminated
- 


















































